### ISSUE TITLE
Give credit to pyimagesearch blog post

### ISSUE THREAD

**Issue by kas** [vipul-sharma20/document-scanner#3]
I noticed someone in the HN [thread](https://news.ycombinator.com/item?id=12104704) posted about how a blog post from 2014 had the same code as found in this repository.

We should give that pyimagesearch blog post credit in the README

**Comment by vipul-sharma20** [comment]
Yes, I totally understand the concern. I obviously referred the blog post and there was no intention of mine to plagiarize the content and take sole credit. I am deeply indebted to the open source community and to all the people sharing their knowledge on the internet. Its because of people like them, I am able to learn and grow throughout.

I'll do the needful and add credits to the article wherever possible.
Thanks.
